[versions]
#gradle = "8.0.0-alpha11"
gradle = "7.4.0-rc03"
kotlin = "1.7.10"
dagger = "2.44.2"
gms = "4.3.14"
crashlytics = "2.9.2"

coroutines = "1.3.9"

test-junit = "4.13"
test-mockito = "3.5.10"
test-mockito-kotlin = "2.2.0"
test-livedata = "1.1.2"
test-robolectric = "4.8.1"
testui-androidx = "1.4.0"

[libraries]
plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
plugin-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
plugin-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-mockito = { module = "org.mockito:mockito-android", version.ref = "test-mockito" }
test-mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "test-mockito" }
test-mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "test-mockito-kotlin" }
test-livedata = { module = "com.jraska.livedata:testing-ktx", version.ref = "test-livedata" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
testui-runner = { module = "androidx.test:runner", version.ref = "testui-androidx" }
testui-rules = { module = "androidx.test:rules", version.ref = "testui-androidx" }