[versions]
gradle = "7.0.2"
kotlin = "1.6.0"
gms = "4.3.3"
crashlytics = "2.2.1"

coroutines = "1.3.9"
dagger = "2.41"

androidx-core = "1.3.1"
androidx-legacy = "1.0.0"
androidx-appcompat = "1.2.0"
androidx-media = "1.4.3"
androidx-recycler = "1.1.0"
androidx-browser = "1.2.0"
androidx-material = "1.2.0"
androidx-preference = "1.1.1"
androidx-palette = "1.0.0"
androidx-annotations = "1.1.0"
androidx-coordinator = "1.1.0"
androidx-fragments = "1.2.5"
androidx-constraintlayout = "2.0.0"
androidx-lifecycle = "2.2.0"

firebase-core = "17.2.0"
firebase-crashlytics = "17.2.1"

glide = "4.11.0"
lottie = "3.4.2"
custom-tabs = "3.0.1"
material-dialogs = "3.3.0"
scroll-helper = "1.1.4"
blurkit = "1.0.0"
color-desaturation = "1.0.2"
tap-target-view = "2.0.0"

room = "2.4.0"
sql-content-resolver = "1.2.1"
okhttp = "4.8.1"
retrofit = "2.9.0"
gson = "2.8.6"

last-fm-binding = "0.1.2"
aes-crypto = "1.1.0"
fuzzywuzzy = "1.2.0"

leak-canary = "2.10"

junit = "4.13"
mockito-core = "3.5.10"
mockito-kotlin = "2.2.0"

[libraries]
plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-gms = { module = "com.google.gms:google-services", version.ref = "gms" }
plugin-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }

kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-legacy = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recycler" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-annotations-core = { module = "androidx.annotation:annotation", version.ref = "androidx-annotations" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-coordinator = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinator" }
androidx-fragments = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragments" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }

ui-glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
ui-glide-processor = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
ui-scrollhelper = { module = "com.github.ologe:scroll-helper", version.ref = "scroll-helper" }
ui-blurkit = { module = "io.alterac.blurkit:blurkit", version.ref = "blurkit" }
ui-lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
ui-customtabs = { module = "saschpe.android:customtabs", version.ref = "custom-tabs" }
ui-materialdialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "material-dialogs" }
ui-materialdialogs-color = { module = "com.afollestad.material-dialogs:color", version.ref = "material-dialogs" }
ui-colordesaturation = { module = "com.github.ologe:color-desaturation", version.ref = "color-desaturation" }
ui-taptargetview = { module = "com.github.ologe:taptargetview", version.ref = "tap-target-view" }

data-sqlcontentresolver = { module = "com.github.ologe:android-content-resolver-SQL", version.ref = "sql-content-resolver" }
data-room-core = { module = "androidx.room:room-runtime", version.ref = "room" }
data-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
data-room-processor = { module = "androidx.room:room-compiler", version.ref = "room" }
data-room-testing = { module = "com.google.firebase:firebase-core", version.ref = "room" }
data-okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
data-okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
data-retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
data-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
data-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

utils-lastfmbinding = { module = "de.u-mass:lastfm-java", version.ref = "last-fm-binding" }
utils-aescrypto = { module = "com.github.tozny:java-aes-crypto", version.ref = "aes-crypto" }
utils-fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }
utils-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leak-canary" }

test-junit = { module = "junit:junit", version.ref = "junit" }
test-mockito-core = { module = "org.mockito:mockito-android", version.ref = "mockito-core" }
test-mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito-kotlin" }